version: '3.8'
services:
  engine:
    image: ghcr.io/hasura/v3-engine:6c9979ddaad50d476c0996d1ece48f0cf1c8e99d
    platform: linux/amd64
    environment:
      - METADATA_PATH=/metadata/metadata.json
      - AUTHN_CONFIG_PATH=/metadata/auth_config.json
      - OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 3000:3000
    volumes:
      - ./resources:/metadata
    depends_on:
      connector:
        condition: service_healthy
      jaeger:
        condition: service_started
      auth_hook:
        condition: service_started
  auth_hook:
    image: ghcr.io/hasura/v3-dev-auth-webhook
    platform: linux/amd64
    environment:
      OTLP_ENDPOINT: "http://jaeger:4317"
    ports:
      - "3050:3050"
    depends_on:
      jaeger:
        condition: service_started
  connector:
    build: .
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
      OTEL_SERVICE_NAME: "ndc-learn"
    depends_on:
      jaeger:
        condition: service_started
  jaeger:
    image: jaegertracing/all-in-one:1.55
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 4002:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 4317:4317 # OTLP gRPC
      - 4318:4318 # OTLP HTTP
      - 9411:9411
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: "9411"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./resources/prometheus/prometheus.yaml
        target: /etc/prometheus/prometheus.yaml